### ISSUE TITLE
"Server correctly resyncs when server leaves and rejoins a room" is flaky on redis

### ISSUE THREAD

**Issue by richvdh** [matrix-org/sytest#918]
see https://buildkite.com/matrix-dot-org/synapse/builds/10133#97f168a4-b442-4d80-88bd-db3615aa36d1

**Comment by richvdh** [comment]
Also: https://buildkite.com/matrix-dot-org/synapse/builds/10734#8ad8cc7d-4249-4d45-889f-ea98d6b96174

**Comment by richvdh** [comment]
Also: https://buildkite.com/matrix-dot-org/synapse/builds/10734#8ad8cc7d-4249-4d45-889f-ea98d6b96174

**Comment by richvdh** [comment]
both these tests have the following stack trace in the event persister:

```
2020-08-03 18:21:29,417 - synapse.http.server - 83 - ERROR - POST-4516 - Failed handle request via 'ReplicationFederationSendEventsRestServlet': <SynapseRequest at 0x7fa470105cf8 method='POST' uri='/_synapse/replication/fed_send_events/veazTVOUtS' clientproto='HTTP/1.1' site=8828>
Traceback (most recent call last):
  File "/venv/lib/python3.7/site-packages/twisted/internet/defer.py", line 1416, in _inlineCallbacks
    result = result.throwExceptionIntoGenerator(g)
  File "/venv/lib/python3.7/site-packages/twisted/python/failure.py", line 512, in throwExceptionIntoGenerator
    return g.throw(self.type, self.value, self.tb)
  File "/venv/lib/python3.7/site-packages/synapse/replication/http/federation.py", line 123, in _handle_request
    event_and_contexts, backfilled
  File "/venv/lib/python3.7/site-packages/synapse/handlers/federation.py", line 2923, in persist_events_and_notify
    event_and_contexts, backfilled=backfilled
  File "/venv/lib/python3.7/site-packages/synapse/storage/persist_events.py", line 226, in persist_events
    defer.gatherResults(deferreds, consumeErrors=True)
twisted.internet.defer.FirstError: FirstError[#0, [Failure instance: Traceback: <class 'psycopg2.errors.UniqueViolation'>: duplicate key value violates unique constraint "event_edges_event_id_prev_event_id_room_id_is_state_key"
DETAIL:  Key (event_id, prev_event_id, room_id, is_state)=($pF8-osunXrgq6N1bgPG-fKJytH6EGD4ZVOwkzB7HKdo, $AdLz-v32Ga6bMXRzLVoHUh82bAbFMfpkDUcwD8YPCxM, !ikCrKnRJwMwPeNENTq:localhost:8831, f) already exists.

/venv/lib/python3.7/site-packages/twisted/internet/defer.py:654:_runCallbacks
/venv/lib/python3.7/site-packages/twisted/internet/defer.py:1475:gotResult
/venv/lib/python3.7/site-packages/twisted/internet/defer.py:1416:_inlineCallbacks
/venv/lib/python3.7/site-packages/twisted/python/failure.py:512:throwExceptionIntoGenerator
--- <exception caught here> ---
/venv/lib/python3.7/site-packages/synapse/storage/persist_events.py:148:handle_queue_loop
/venv/lib/python3.7/site-packages/synapse/storage/persist_events.py:254:persisting_queue
/venv/lib/python3.7/site-packages/synapse/storage/persist_events.py:430:_persist_events
/venv/lib/python3.7/site-packages/twisted/internet/defer.py:1416:_inlineCallbacks
/venv/lib/python3.7/site-packages/twisted/python/failure.py:512:throwExceptionIntoGenerator
/venv/lib/python3.7/site-packages/synapse/util/patch_inline_callbacks.py:144:check_yield_points_inner
/venv/lib/python3.7/site-packages/twisted/python/failure.py:512:throwExceptionIntoGenerator
/venv/lib/python3.7/site-packages/synapse/storage/data_stores/main/events.py:216:_persist_events_and_state_updates
/venv/lib/python3.7/site-packages/synapse/util/patch_inline_callbacks.py:192:check_yield_points_inner
/venv/lib/python3.7/site-packages/twisted/internet/defer.py:1416:_inlineCallbacks
/venv/lib/python3.7/site-packages/twisted/python/failure.py:512:throwExceptionIntoGenerator
/venv/lib/python3.7/site-packages/synapse/util/patch_inline_callbacks.py:144:check_yield_points_inner
/venv/lib/python3.7/site-packages/twisted/python/failure.py:512:throwExceptionIntoGenerator
/venv/lib/python3.7/site-packages/synapse/storage/database.py:527:runInteraction
/venv/lib/python3.7/site-packages/synapse/util/patch_inline_callbacks.py:192:check_yield_points_inner
/venv/lib/python3.7/site-packages/twisted/internet/defer.py:1416:_inlineCallbacks
/venv/lib/python3.7/site-packages/twisted/python/failure.py:512:throwExceptionIntoGenerator
/venv/lib/python3.7/site-packages/synapse/util/patch_inline_callbacks.py:144:check_yield_points_inner
/venv/lib/python3.7/site-packages/twisted/python/failure.py:512:throwExceptionIntoGenerator
/venv/lib/python3.7/site-packages/synapse/storage/database.py:575:runWithConnection
/venv/lib/python3.7/site-packages/synapse/util/patch_inline_callbacks.py:192:check_yield_points_inner
/venv/lib/python3.7/site-packages/twisted/python/threadpool.py:250:inContext
/venv/lib/python3.7/site-packages/twisted/python/threadpool.py:266:<lambda>
/venv/lib/python3.7/site-packages/twisted/python/context.py:122:callWithContext
/venv/lib/python3.7/site-packages/twisted/python/context.py:85:callWithContext
/venv/lib/python3.7/site-packages/twisted/enterprise/adbapi.py:306:_runWithConnection
/venv/lib/python3.7/site-packages/twisted/python/compat.py:464:reraise
/venv/lib/python3.7/site-packages/twisted/enterprise/adbapi.py:297:_runWithConnection
/venv/lib/python3.7/site-packages/synapse/storage/database.py:572:inner_func
/venv/lib/python3.7/site-packages/synapse/storage/database.py:416:new_transaction
/venv/lib/python3.7/site-packages/synapse/logging/utils.py:71:wrapped
/venv/lib/python3.7/site-packages/synapse/storage/data_stores/main/events.py:452:_persist_events_txn
/venv/lib/python3.7/site-packages/synapse/storage/data_stores/main/events.py:948:_update_metadata_tables_txn
/venv/lib/python3.7/site-packages/synapse/storage/data_stores/main/events.py:1468:_handle_mult_prev_events
/venv/lib/python3.7/site-packages/synapse/storage/database.py:685:simple_insert_many_txn
/venv/lib/python3.7/site-packages/synapse/storage/database.py:211:executemany
/venv/lib/python3.7/site-packages/synapse/storage/database.py:234:_do_execute
]]
```

**Comment by richvdh** [comment]
before that, this happens:

```
2020-08-03 18:21:29,044 - synapse.replication.http.membership - 83 - INFO - POST-5074 - remote_join: @anon-20200803_181310-765:localhost:8831 into room: !ikCrKnRJwMwPeNENTq:localhost:8831
2020-08-03 18:21:29,045 - synapse.http.matrixfederationclient - 411 - INFO - POST-5074 - {GET-O-90} [localhost:42091] Sending request: GET matrix://localhost:42091/_matrix/federation/v1/make_join/%21ikCrKnRJwMwPeNENTq%3Alocalhost%3A8831/%40anon-20200803_181310-765%3Alocalhost%3A8831?ver=1&ver=2&ver=3&ver=4&ver=5&ver=6; timeout 20.000000s
2020-08-03 18:21:29,047 - synapse.replication.tcp.resource - 158 - INFO - replication_notifier-11921 - Streaming: caches -> 6333
2020-08-03 18:21:29,058 - synapse.http.matrixfederationclient - 162 - INFO - POST-5074 - {GET-O-90} [localhost:42091] Completed: 200 OK
2020-08-03 18:21:29,062 - synapse.http.matrixfederationclient - 411 - INFO - POST-5074 - {PUT-O-91} [localhost:42091] Sending request: PUT matrix://localhost:42091/_matrix/federation/v2/send_join/%21ikCrKnRJwMwPeNENTq%3Alocalhost%3A8831/%24AdLz-v32Ga6bMXRzLVoHUh82bAbFMfpkDUcwD8YPCxM; timeout 60.000000s
2020-08-03 18:21:29,068 - synapse.http.matrixfederationclient - 162 - INFO - POST-5074 - {PUT-O-91} [localhost:42091] Completed: 200 OK
2020-08-03 18:21:29,076 - synapse.http.client - 301 - INFO - POST-5074 - Sending request POST http://localhost:8828/_synapse/replication/fed_send_events/SNqeenpAem
2020-08-03 18:21:29,090 - synapse.http.client - 340 - INFO - POST-5074 - Received response to POST http://localhost:8828/_synapse/replication/fed_send_events/SNqeenpAem: 200
2020-08-03 18:21:29,098 - synapse.http.client - 301 - INFO - POST-5074 - Sending request POST http://localhost:8828/_synapse/replication/fed_send_events/RfHFsdzwlu
2020-08-03 18:21:29,152 - synapse.http.client - 340 - INFO - POST-5074 - Received response to POST http://localhost:8828/_synapse/replication/fed_send_events/RfHFsdzwlu: 200
2020-08-03 18:21:29,152 - synapse.replication.tcp.client - 228 - INFO - POST-5074 - Waiting for repl stream 'events' to reach 4552
2020-08-03 18:21:29,177 - synapse.replication.tcp.client - 231 - INFO - POST-5074 - Finished waiting for repl stream 'events' to reach 4552
2020-08-03 18:21:29,183 - synapse.http.server - 74 - INFO - POST-5074 - <SynapseRequest at 0x7f371dfd66a0 method='POST' uri='/_synapse/replication/remote_join/%21ikCrKnRJwMwPeNENTq%3Alocalhost%3A8831/%40anon-20200803_181310-765%3Alocalhost%3A8831/hPzlOLptoH' clientproto='HTTP/1.1' site=8801> SynapseError: 404 - Unknown room 
```

... which suggests that the first join attempt has raced against something else, failed, and left things in a mess.

**Comment by richvdh** [comment]
This, presumably, is what it races against:

```
2020-08-03 18:21:29,100 - synapse.replication.http.federation - 120 - INFO - POST-4514 - Got 1 events from federation
2020-08-03 18:21:29,109 - synapse.state - 485 - INFO - persist_events-4386 - Resolving state for !ikCrKnRJwMwPeNENTq:localhost:8831 with 2 groups
2020-08-03 18:21:29,109 - synapse.state - 508 - INFO - persist_events-4386 - Resolving conflicted state for '!ikCrKnRJwMwPeNENTq:localhost:8831'
2020-08-03 18:21:29,127 - synapse.storage.persist_events - 413 - INFO - persist_events-4386 - Server no longer in room !ikCrKnRJwMwPeNENTq:localhost:8831
2020-08-03 18:21:29,142 - synapse.replication.tcp.resource - 158 - INFO - replication_notifier-5890 - Streaming: caches -> 6334
2020-08-03 18:21:29,150 - synapse.access.http.8828 - 310 - INFO - POST-4514 - 127.0.0.1 - 8828 - {None} Processed request: 0.050sec/0.000sec (0.000sec, 0.000sec) (0.000sec/0.000sec/0) 22B 200 "POST /_synapse/replication/fed_send_events/RfHFsdzwlu HTTP/1.1" "Synapse/1.18.0 homeserver[0]" [0 dbevts]
```

**Comment by richvdh** [comment]
ok, so the problem here is that Synapse is being slow to send out the leave event over federation (or sytest is being slow to persist it in its federation implementation), which means that then, when the make_join request happens, the join event that sytest returns uses the *previous* event as its prev_event.

So then there is a state resolution, and synapse decides that it's no longer in the room, which seems to confuse the join logic badly.

This is easily fixed in the test, but I'm a bit alarmed that synapse handles it so badly.
